
services:
  # MQTT Broker (HiveMQ or Mosquitto)
  mqtt-broker:
    build:
      context:  ./mqtt
      dockerfile: Dockerfile
    container_name: mosquitto-broker
    restart: always
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - watering_network


  # Backend server
  backend:
    build: 
      context: ./backend
    container_name: auto_watering_backend
    restart: unless-stopped
    depends_on:
      - mysql-db
      - mqtt-broker
    networks:
      - watering_network 
    env_file: ./backend/.env

  mysql-db:
    image: mysql:8.0
    container_name: auto_watering_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: auto_watering_system
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3306:3306"
    depends_on:
      - mqtt-broker
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - watering_network

networks:
  watering_network:
    driver: bridge

volumes:
  mysql_data:

